select * from customer limit 10;

--1.what is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as total_revenue
from customer
group by gender;

--2.which customers used a discount but still spent more than the average purchase amount
select customer_id,purchase_amount
from customer
WHERE discount_applied='Yes' AND purchase_amount >= (select AVG(purchase_amount) from customer)

--3.which are the top 5 products with highest average review rating?
select item_purchased,ROUND(AVG(review_rating::numeric),2) AS "average review rating products"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

--4.compare the average purchase amount between standard and express
select shipping_type,ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5.do subscribed customers spend more? compare average spend and total revenue
--between subscribers and non-subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
SUM(purchase_amount) as total_revenue
from customer
group by subscription_status
order by avg_spend,total_revenue desc;

--6.which 5 products have the highest percentage of purchases with discount applied and without discount_applied?
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate_yes,
ROUND(100*SUM(CASE WHEN discount_applied = 'No' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate_no
from customer
group by item_purchased
order by discount_rate_yes,discount_rate_no desc
limit 5;

--7.segment customer into new,returning, and loyal based on their total
--number of previous_purchases,and show the count of each segment.

SELECT COUNT(customer_id) as customer_count,
CASE
     WHEN previous_purchases = 1 THEN 'New'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
     ELSE 'Loyal'
     END AS customer_segment 
FROM customer
GROUP BY customer_segment
ORDER BY customer_count DESC;

--8.what are the top 3 most purchased products within each category?
WITH product_purchases AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS total_purchases
    FROM customer
    GROUP BY category, item_purchased
),
ranked_products AS (
    SELECT
        category,
        item_purchased,
        total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY total_purchases DESC
        ) AS rank_num
    FROM product_purchases
)
SELECT
    category,
    item_purchased,
    total_purchases,
    rank_num
FROM ranked_products
WHERE rank_num <= 3
ORDER BY category, rank_num;

--9.Are customers who are repeat buyers(more than 5 previous purchases) also likely
--to subscribe?
WITH customer_segments AS (
    SELECT
        customer_id,
        CASE
            WHEN previous_purchases > 5 THEN 'Repeat Buyer'
            ELSE 'Non-Repeat Buyer'
        END AS customer_type,
        subscription_status
    FROM customer
)
SELECT
    customer_type,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribers
    FROM customer_segments
GROUP BY customer_type;

--10.find the revenue contribution of each age group?
select age_group,SUM(purchase_amount) as revenue_contribution
from customer
group by age_group
order by revenue_contribution desc;
